analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.502467
  lightness: 0.680098
  rhythmicContrast: 0.710526
  saturation: 0.930916
cta: {}
layout_spectrum: 0.521381
name: ashtanga.yoga
opengraph: {}
purpose: {}
typography_spectrum: 0.778782
